### ISSUE TITLE
Showcase how to bundle `supplyCollateral` + `borrow` when only input `marketParams` & `borrowed` are known

### ISSUE THREAD

**Issue by Rubilmax** [morpho-org/morpho-blue-snippets#28]
1. `supplyCollateral(borrowed / lltv)`
  a. `borrow(borrowed)`
  b. `out = swap(borrowed)`
2. `supplyCollateral(out - borrowed / lltv)`

is equivalent to

1. `borrow(borrowed)`
  a. `out = swap(borrowed)`
  b. `supplyCollateral(out)`

**Comment by Jean-Grimal** [comment]
I'm not sure to understand the issue @Rubilmax.

Should it be done in MorphoBlueSnippets or CallbackSnippets ? And what amount of collateral should be supplied ? The minimum amount to be able to borrow the known `borrowed` amount ?

**Comment by Rubilmax** [comment]
It seems if one can swap `borrowed` for `out` then price is approx `borrowed/out` so it only works if `lltv` is 100%... So this issue is incorrect to me
